### ISSUE TITLE
Not all photos has been processed

### ISSUE THREAD

**Issue by malteschlueter** [peter-sk/photosdup#1]
Hello,

thank you very much for your great work :)

Unfortunately it will not process all of my ~30.000 pictures. It's processing only 8.087 pictures :/

I'm just using it with the `--tag` option.

Do I have to download all pictures to my computer before executing?
Or do I've to set a specific option when executing?

Thanks for your help :)

**Comment by peter-sk** [comment]
Hallo Malte,

I assume you do read German. If not (or you prefer another language), let me know 😊

Im Moment gehe ich davon aus, dass die Bibliothek lokal auf dem Computer downgeloadet ist. Ich nehme Cloud-Unterstuetzung mal in die TODO-Liste auf!

Gruss,
Peter

From: Malte Schlüter ***@***.***>
Date: Wednesday, 13 July 2022 at 20.10
To: peter-sk/photosdup ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [peter-sk/photosdup] Not all photos has been processed (Issue #1)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Hello,

thank you very much for your great work :)

Unfortunately it will not process all of my ~30.000 pictures. It's processing only 8.087 pictures :/

I'm just using it with the --tag option.

Do I have to download all pictures to my computer before executing?
Or do I've to set a specific option when executing?

Thanks for your help :)

**Comment by malteschlueter** [comment]
Deutsch passt^^

Wenn ich die iCloud einstelle, dass die Originale lokal gespeichert werden sollen, scheint es tatsächlich zu funktionieren. Zumindest hat das Script nun schon ca. 8.500 Fotos verarbeitet.

Apple könnte den Download-Prozess auf jeden Fall mal beschleunigen, da hilft leider meine 1Gbit Leitung auch nicht^^

Vielen Dank auf jeden Fall für die Hilfe :)

**Comment by peter-sk** [comment]
Evtl. kannst Du das mit folgendem Kommando beschleunigen:

sudo sysctl debug.lowpri_throttle_enabled=0


From: Malte Schlüter ***@***.***>
Date: Wednesday, 13 July 2022 at 21.21
To: peter-sk/photosdup ***@***.***>
Cc: Peter Schneider-Kamp ***@***.***>, Comment ***@***.***>
Subject: Re: [peter-sk/photosdup] Not all photos has been processed (Issue #1)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Deutsch passt^^

Wenn ich die iCloud einstelle, dass die Originale lokal gespeichert werden sollen, scheint es tatsächlich zu funktionieren. Zumindest hat das Script nun schon ca. 8.500 Fotos verarbeitet.

Apple könnte den Download-Prozess auf jeden Fall mal beschleunigen, da hilft leider meine 1Gbit Leitung auch nicht^^

Vielen Dank auf jeden Fall für die Hilfe :)

**Comment by peter-sk** [comment]
You might want to try the new --thumbs option. This speeds up the whole process tremendously (except the tagging, which is limited by AppleScript).
